version: "3"

services:
  sveltekit-test:
    image: ghcr.io/naabu/naabu_sveltekit:<GITHUB_SHA>
    volumes:
      - ./config/:/var/www/config
    entrypoint: ["npm", "run", "dev"]
    environment:
      - environment=test
    networks:
      - internal_network

  firebase:
    image: ghcr.io/naabu/naabu_firebase:<GITHUB_SHA>
    volumes:
      - ./config/:/var/www/config
    environment:
      - environment=test
    entrypoint: ["npm", "run", "emulateCypress"]
    networks:
      - internal_network

  playwright:
    image: ghcr.io/naabu/naabu_playwright:<GITHUB_SHA>
    volumes:
      - ./test-results/:/var/www/test-results
    environment:
      - CI=true
    networks:
      - internal_network

networks:
  internal_network:
