version: "3"

services:
  sveltekit-test:
    build:
      context: .
      dockerfile: dockerfiles/sveltekit/dev/Dockerfile
    entrypoint: ["npm", "run", "dev"]
    environment:
      - environment=test
    networks:
      - internal_network

  firebase:
    build:
      context: .
      dockerfile: dockerfiles/sveltekit/dev/Dockerfile
    environment:
      - environment=test
    entrypoint: ["npm", "run", "emulateCypress"]
    secrets:
      - algolia-private-api-key
    networks:
      - internal_network

  playwright:
    build:
      context: .
      dockerfile: dockerfiles/playwright/Dockerfile
    volumes:
      - ./test-results/:/var/www/test-results
    environment:
      - CI=true
    networks:
      - internal_network

secrets:
  algolia-private-api-key:
    file: ./config/algolia-secret-admin-api-key.txt
networks:
  internal_network:
