version: "3"

services:
  sveltekit-test:
    image: ghcr.io/naabu/naabu_sveltekit<EXTRA>:<GITHUB_SHA>
    volumes:
      - ./config/:/var/www/config
    entrypoint: ["npm", "run", "dev"]
    environment:
      - environment=test
      - defaultLanguage="en"
    networks:
      - internal_network

  firebase:
    image: ghcr.io/naabu/naabu_firebase<EXTRA>:<GITHUB_SHA>
    volumes:
      - ./config/:/var/www/config
    environment:
      - environment=test
    entrypoint: ["npm", "run", "emulateCypress"]
    networks:
      - internal_network

  playwright:
    image: ghcr.io/naabu/naabu_playwright<EXTRA>:<GITHUB_SHA>
    volumes:
      - ./test-results/:/var/www/test-results
    environment:
      - CI=true
    networks:
      - internal_network

networks:
  internal_network:
