name: Build and test latest code

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker://ghcr.io/naabu/naabu_sveltekit-core:v0.0.1
      - uses: docker://ghcr.io/naabu/naabu_firebase-core:v0.0.1
      - uses: docker://ghcr.io/naabu/naabu_playwright-core:v0.0.1
      - uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - run: docker build . --file dockerfiles/sveltekit/dev/Dockerfile  --tag naabu-image:$GITHUB_SHA
      - run: docker-compose -f ci/build-code-sha-docker-compose.yml build
      - run: docker tag ci_firebase-code:latest ghcr.io/naabu/naabu_firebase:${GITHUB_SHA}
      - run: docker tag ci_sveltekit-test:latest ghcr.io/naabu/naabu_sveltekit:${GITHUB_SHA}
      - run: docker tag ci_playwright-code:latest ghcr.io/naabu/naabu_playwright:${GITHUB_SHA}
      - run: |
          docker images
      - run: docker push ghcr.io/naabu/naabu_firebase:${GITHUB_SHA}
      - run: docker push ghcr.io/naabu/naabu_sveltekit:${GITHUB_SHA}
      - run: docker push ghcr.io/naabu/naabu_playwright:${GITHUB_SHA}

  test-playwright:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      ALGOLIA_PRIVATE_API_KEY: ${{ secrets.ALGOLIA_PRIVATE_API_KEY }}
      ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      ALGOLIA_SEARCH_ONLY_API_KEY: ${{ secrets.ALGOLIA_SEARCH_ONLY_API_KEY }}
      FB_API_KEY: ${{ secrets.FB_API_KEY }}
      FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
      FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
      FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
      FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }},
      FB_APP_ID: ${{ secrets.FB_APP_ID }}
      FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}
    steps:
      - uses: docker://ghcr.io/naabu/naabu_sveltekit-core:v0.0.1
      - uses: docker://ghcr.io/naabu/naabu_firebase-core:v0.0.1
      - uses: docker://ghcr.io/naabu/naabu_playwright-core:v0.0.1
      - uses: actions/checkout@v2
      - run: |
          ls -lah
      - run: sed
          -e "s/<ALGOLIA_APPLICATION_ID>/$ALGOLIA_APPLICATION_ID/"
          -e "s/<ALGOLIA_SEARCH_ONLY_API_KEY>/$ALGOLIA_SEARCH_ONLY_API_KEY/"
          config/example-config-algolia.js > config/config-algolia.js
      - run: sed
          -e "s/<FB_API_KEY>/$FB_API_KEY/"
          -e "s/<FB_AUTH_DOMAIN>/$FB_AUTH_DOMAIN/"
          -e "s/<FB_PROJECT_ID>/$FB_PROJECT_ID/"
          -e "s/<FB_STORAGE_BUCKET>/$FB_STORAGE_BUCKET/"
          -e "s/<FB_MESSAGING_SENDER_ID>/$FB_MESSAGING_SENDER_ID/"
          -e "s/<FB_APP_ID>/$FB_APP_ID/"
          -e "s/<FB_MEASUREMENT_ID>/$FB_MEASUREMENT_ID/"
          config/example-config-firebase.js > config/config-firebase.js
      - run: |
          ls -lah config/
      - run: rm -rf node_modules
      - run: rm -rf test-results
      - run: rm -rf config/algolia-secret-admin-api-key.txt
      - run: echo -n $ALGOLIA_PRIVATE_API_KEY >> config/algolia-secret-admin-api-key.txt
      - run: |
          ls -lah
      - run: sed -e "s/<GITHUB_SHA>/$GITHUB_SHA/" ci/actions-docker-compose.yml > sha-docker-compose.yml
      - run: docker-compose -f sha-docker-compose.yml up -d --remove-orphans
      - run: sleep 40
      - run: docker-compose -f sha-docker-compose.yml logs sveltekit-test
      - run: docker-compose -f sha-docker-compose.yml logs firebase
      - run: echo "running ping tests"
      - run: docker-compose -f sha-docker-compose.yml exec -T playwright npx playwright test --project=docker --grep @ping
      - run: echo "running playwright goal tests"
      - run: docker-compose -f sha-docker-compose.yml exec -T playwright npx playwright test --project=docker --grep @goal
      - run: docker-compose -f sha-docker-compose.yml logs sveltekit-test
      - run: docker-compose -f sha-docker-compose.yml logs firebase
      - run: echo "running playwright activity tests"
      - run: docker-compose -f sha-docker-compose.yml exec -T playwright npx playwright test --project=docker --grep @activity
      - run: docker-compose -f sha-docker-compose.yml logs sveltekit-test
      - run: docker-compose -f sha-docker-compose.yml logs firebase
      - run: echo "running playwright module tests"
      - run: docker-compose -f sha-docker-compose.yml exec -T playwright npx playwright test --project=docker --grep @module
      - run: docker-compose -f sha-docker-compose.yml logs sveltekit-test
      - run: docker-compose -f sha-docker-compose.yml logs firebase
      - name: Display Firebase logs on failure
        if: ${{ failure() }}
        run: docker-compose -f sha-docker-compose.yml logs firebase
      - name: Display SvelteKit logs on failure
        if: ${{ failure() }}
        run: docker-compose -f sha-docker-compose.yml logs sveltekit-test
