name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      ALGOLIA_CONFIG: ${{ secrets.ALGOLIA_CONFIG }}
      ALGOLIA_PRIVATE_API_KEY: ${{ secrets.ALGOLIA_PRIVATE_API_KEY }}
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    steps:
    - uses: actions/checkout@v2
    - run: rm -rf node_modules
    - run: rm -rf test-results
    - run: rm -rf config/algolia-secret-admin-api-key.txt
    - run: rm -rf config/config-algolia.js
    - run: rm -rf config/config-firebase.js
    - run: echo -n $ALGOLIA_KEY >> config/algolia-secret-admin-api-key.txt
    - run: echo -n $ALGOLIA_CONFIG >> config/config-algolia.js
    - run: echo -n $FIREBASE_CONFIG >> config/config-firebase.js
    - run: cat config/config-firebase.js
    - run: cat config/config-algolia.js
    - run: ls ${{ github.workspace }}/config
    # - run: docker build . --file dockerfiles/sveltekit/dev/Dockerfile  --tag naabu-image:$GITHUB_SHA
    - run: docker-compose -f jenkins-docker-compose.yml build
    - run: docker-compose -f jenkins-docker-compose.yml up -d --remove-orphans
    - run: sleep 60
    - run: docker-compose -f jenkins-docker-compose.yml logs sveltekit-test
    - run: docker-compose -f jenkins-docker-compose.yml logs firebase
    - run: docker-compose -f jenkins-docker-compose.yml exec -T -d sveltekit-test cat /var/www/config/config-firebase.js
    - run: docker-compose -f jenkins-docker-compose.yml exec -T -d sveltekit-test cat /var/www/config/config-algolia.js
