name: Build Jekyll Storybook and publish to Github pages

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cp ci/github-pages-jekyll-storybook.yml .
      - run: docker-compose -f github-pages-jekyll-storybook.yml up
      - name: "Build jekyll"
        uses: actions/jekyll-build-pages@v1-beta
        with:
          source: "./docs"
          destination: "./docs/_site"
      - run: pwd
      - run: ls -lah
      - run: ls -lah docs/
      - name: "Create archive of docs folder"
        run: tar --dereference --hard-dereference --directory docs/_site/ -cvf artifact.tar .
      - name: "Upload artifact"
        uses: actions/upload-artifact@main
        with:
            name: github-pages
            path: ./artifact.tar
  
  deploy:
    runs-on: ubuntu-latest
    needs: "build"
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy Documnetation and Storybook on Github pages.
        uses: actions/deploy-pages@v1-beta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
