name: Build Jekyll Storybook and publish to Github pages

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull ghcr.io/actions/jekyll-build-pages:v1-beta
      - uses: actions/checkout@v2
      - run: cp ci/github-pages-jekyll-storybook.yml .
      - run: docker-compose -f github-pages-jekyll-storybook.yml up
      - name: "Build jekyll"
        uses: actions/jekyll-build-pages@v1-beta
        with:
          source: "./docs"
          destination: "./docs/_site"
